#image: centos:latest
image: michaelrichard/builder:v0.2

variables:
  NODE_ENV: "test"
  GIT_SSL_NO_VERIFY: "true"

stages:
  - build
  - terraform_plan
  - terraform_apply
  - terraform_destroy
before_script:
   - terraform_url=$(curl https://releases.hashicorp.com/index.json 2>/dev/null| jq -r '{terraform}' | grep url| egrep "linux.*amd64" | sort -n -r | grep -v 'alpha\|beta' | head -n1 | awk '{print $2}' | xargs echo)
   - curl -o terraform.zip $terraform_url
   - unzip -o terraform.zip -d "/usr/local/bin/"
   - terraform --version
   - which terraform
   - echo -e "[default]\naws_access_key_id = ${AWS_ID}\naws_secret_access_key = ${AWS_KEY}" > ~/.aws/credentials

.build: &build
  stage: build
  script:
   - cd lambda
   - ./build.sh
  artifacts:
    expire_in: 24h
    when: always
    paths:
      - lambda/lambda.py.zip

.terraform_plan: &terraform_plan
  stage: terraform_plan
  script:
    - cd terraform
    - echo "REDDIT_CLIENT_ID = \"${REDDIT_CLIENT_ID}\"" >> terraform.tfvars
    - echo "REDDIT_CLIENT_SECRET = \"${REDDIT_CLIENT_SECRET}\"" >> terraform.tfvars
    - echo "REDDIT_CLIENT_USERNAME = \"${REDDIT_CLIENT_USERNAME}\"" >> terraform.tfvars
    - echo "REDDIT_CLIENT_PASSWORD = \"${REDDIT_CLIENT_PASSWORD}\"" >> terraform.tfvars
    - echo "REDDIT_SUBREDDIT = \"${REDDIT_SUBREDDIT}\""  >> terraform.tfvars
    - if [ ! -z "$SCHEDULE" ] ; then echo "SCHEDULE = \"${SCHEDULE}\"" >> terraform.tfvars; fi
    - cat terraform.tfvars | awk '{ print $1}'
    - terraform init -reconfigure -backend-config=${REDDIT_SUBREDDIT}.tfbackend
    - terraform plan -out tfplan
  artifacts:
    expire_in: 24h
    when: always
    paths:
      - lambda/lambda.py.zip
      - terraform/tfplan
      - terraform/terraform.tfvars

.terraform_apply: &terraform_apply
  stage: terraform_apply
  script:
    - cd terraform
    - terraform init
    - terraform apply -auto-approve tfplan

common_build:
  variables:
  <<: *build

rippletest_terraform_plan:
  dependencies:
    - common_build
  variables:
    REDDIT_SUBREDDIT: "rippletest"
    SCHEDULE: "10 minutes"
  <<: *terraform_plan

rippletest_terraform_apply:
  dependencies:
    - common_build
    - rippletest_terraform_plan
  <<: *terraform_apply

ripple_terraform_plan:
  dependencies:
    - common_build
  variables:
    REDDIT_SUBREDDIT: "ripple"
    SCHEDULE: "10 minutes"
  <<: *terraform_plan

ripple_terraform_apply:
  when: manual
  only:
    - master
  dependencies:
    - common_build
    - ripple_terraform_plan
  <<: *terraform_apply
