#image: centos:latest
image: michaelrichard/builder:v0.2

variables:
  NODE_ENV: "test"
  REDDIT_SUBREDDIT: "rippletest"

stages:
  - terraform_test_plan
  - terraform_apply
  - terraform_destroy

before_script:
# Add secret vars
   - echo -e "[default]\naws_access_key_id = ${AWS_ID}\naws_secret_access_key = ${AWS_KEY}" > ~/.aws/credentials
   - echo "REDDIT_CLIENT_ID = \"${REDDIT_CLIENT_ID}\"" >> ./terraform/terraform.tfvars
   - echo "REDDIT_CLIENT_SECRET = \"${REDDIT_CLIENT_SECRET}\"" >> ./terraform/terraform.tfvars
   - echo "REDDIT_CLIENT_USERNAME = \"${REDDIT_CLIENT_USERNAME}\"" >> ./terraform/terraform.tfvars
   - echo "REDDIT_CLIENT_PASSWORD = \"${REDDIT_CLIENT_PASSWORD}\"" >> ./terraform/terraform.tfvars
   - cd lambda
   - ./build.sh

.terraform_plan: &terraform_plan
  stage: terraform_plan
  script:
    - echo "REDDIT_SUBREDDIT = \"${REDDIT_SUBREDDIT}\""  >> ./terraform/terraform.tfvars
    - cd terraform
    - terraform init
    - terraform plan -out tfplan
  artifacts:
    expire_in: 24h
    when: always
    paths:
      - lambda/lambda.py.zip
      - terraform/tfplan

terraform_test_plan:
  <<: *terraform_plan
